### ISSUE TITLE
mootensai/jsblock * -> no matching package found.

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mootensai/yii2-enhanced-gii \* -> satisfiable by mootensai/yii2-enhanced-gii[0.0.1].
    - mootensai/yii2-enhanced-gii 0.0.1 requires mootensai/jsblock \* -> no matching package found.

Not uploaded yet?

**Comment by mootensai** [comment]
I have fix this. Please try again..

**Comment by arjenmeijer** [comment]
Thanks. It works!
