### ISSUE TITLE
I am lost with queries and search

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#10]
It is getting better and better. Thank you!

However, I do not understand the query and search options. That is, the query option generates an include like:
use app\models\Name;
use NameQuery;
Hence, the query class is not found, as it should be in app\models.

update: You are using different namespaces. Can I read somewhere an overview of your thinking and setup?

Moreover, if I change it manually, I run into troubles with query and search classes.
Default search is used, but you use query. Why the name change?

if I generate an active record query class I get the error:
Missing argument 1 for yii\db\ActiveQuery::__construct(), called in /var/www/html/pro.3de5.nl/controllers/NameController.php on line 35 and defined

**Comment by mootensai** [comment]
will be fixed by next update.. don't forget to use dev-master version
