### ISSUE TITLE
Expandable / collapsible row and Pagination

### ISSUE THREAD

**Issue by indigitale** [mootensai/yii2-enhanced-gii#101]
Hi all, 

thanks for your great job.
I have a problem with pagination on expandable row. I see the first 20 items of "child" table, but if i click to view the second page, i see "No result found.".
Can you help me?
Thanks!

**Comment by indigitale** [comment]
Anyone have the same problem?
Thanks!

**Comment by mootensai** [comment]
Not happening to me.
How to reproduce this issue?

**Comment by mootensai** [comment]
Is there anybody get this issue? I will close this issue until there's someone reply a confirmed bug n find a way to reproduce this issue..
