### ISSUE TITLE
related don't get deleted

### ISSUE THREAD

**Issue by ragua** [mootensai/yii2-enhanced-gii#102]
Hello, same issue as #77.
I update to dev-master version, but the last record is never deleted.

Here is my controller:

    public function actionDevis($id)
    {
        $model = $this->findModel($id);
        $modelsDevis = $model->devis;
    
        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) 
        {
            // on affiche la vue du BAT
            return $this->redirect(['view', 'id' => $model->bat_id]);
        }
        else 
        {
            return $this->render('_formDevis', [
                'model' => $model,
                'modelsDevis' => (empty($modelsDevis)) ? [new Devis] : $modelsDevis
            ]);
       }
    }

Thanks in advance for your help.

**Comment by mootensai** [comment]
Not happening to me. I'll close this issue for now until I can verify this issue by send me your schema/database dump.
