### ISSUE TITLE
Compatibility with yii2-user and Suggested Enhancement

### ISSUE THREAD

**Issue by skills-up** [mootensai/yii2-enhanced-gii#104]
Hi,

The plugin is programmed to use the default app user id class by default, and hence I've to manually change the class reference to 'dektrium\user\models\User' for using it along with https://github.com/dektrium/yii2-user plugin. Is there a way to configure the class reference to use?

Further, is there a way to use username instead of id for created_by and modified_by (blameable) behavior? This could be a very useful enhancement.

**Comment by mootensai** [comment]
no, i won't create generator to generate compatible version of yii2-user. you have to manually edit the model.

yes, you could change the BlameableBehavior value

**Comment by cgernert** [comment]
Try to inherit the default user class as described and override the model's functions as needed.
Works for me, no problem. You have to edit this sooner or later anyway, e. g. when you want to add additional functionality for your user model.
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md
