### ISSUE TITLE
UUID behaviours

### ISSUE THREAD

**Issue by ednotorres** [mootensai/yii2-enhanced-gii#105]
Hello. Sorry for bothering you. I'm trying to find a mootensai enhance gii documentation. As I can't find it, i have to ask you: I'm designing a table and I want use UUID generator using enhancement gii. What is the size of the id column and it's type? I think I can use varchar 20. I tried use int and had som troubles. I'm using MySQL. 
Another question: when the table has related tables, the enhanced gii creates a modular form as (I think, a way of make things easier). If I comment the tabular form code and update the data on the main table, all related data is deleted. Can I avoid it even commenting the modular form code?
Thanks. You make my job easier and faster.

**Comment by cgernert** [comment]
Hi,

I use char(32) for my UUIDs and it works fine.
Take a look at line 88
https://github.com/mootensai/yii2-relation-trait/blob/master/RelationTrait.php
For the saveAll function you can specify an array of related tables, that
should be skipped, thus data will not be deleted by a missing form.

Best
Christoph

**Comment by ednotorres** [comment]
Thank you. I'll do that and feedback.

**Comment by ednotorres** [comment]
Hi again. Feeding back: I'm getting crazy with skippedRelation.
I can't find any example of using it and have tried set the parameter with the following values: 'tcr_contato', 'tcr-contato', 'TcrContato'.
It's clear that the child table is tcr_contato. I did set the parameter with the database relation name, like: fk_tcr_contato_tcr_pessoa.

Can anyone help me?
Thanks.
:)

**Comment by cgernert** [comment]
Hi, your model's attributes should be uncapitalized. In camel case your
attribute for the table name should be 'tcrContato', if you got a 1:n
relationship going on, use plural: 'tcrContatos'.
To be sure, check your (base) model generated by gii. It should show up as:
 * @property \frontend\models\TaskEvent[] $taskEvents
(in this case the table name is "task_event")

Best
Christoph

**Comment by ednotorres** [comment]
Thanks' for everything.
It's working nice now.
