### ISSUE TITLE
records duplicated after updating 

### ISSUE THREAD

**Issue by klavan88** [mootensai/yii2-enhanced-gii#106]
After updating my parent record, the related records are being duplicated...

**Comment by ednotorres** [comment]
Are you updating or saving as new?

**Comment by medzhidov** [comment]
I had the same trouble. It happens after updating

**Comment by mootensai** [comment]
How to reproduce this issue?                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                            From: notifications@github.comSent: June 24, 2017 00:39To: yii2-enhanced-gii@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [mootensai/yii2-enhanced-gii] records duplicated after updating (#106)  I had the same trouble. It happens after updating

**Comment by medzhidov** [comment]
To reproduce this error follow next steps:
1. Create new record
2. Update this record with adding some relations
3. Update this record again with adding some more relations
4. Ta-da, you will get duplicated relation records

And @mootensai, great thanks for your work, it project very helpful.

**Comment by medzhidov** [comment]
I found new steps to reproduce this trouble:
1. Update any record, that has some related records
2. Ta-da, all related records were duplicate

**Comment by mootensai** [comment]
Not happening to me.. could you send me your schema to my email?

UPDATE: happen on dev-master version

**Comment by mootensai** [comment]
please use yii2-relation-trait stable version, this issue happen on dev-master version

**Comment by mootensai** [comment]
to correct this problem
find line contain `elseif ($AQ->multiple) $notDeletedFK[$key] = "\"$key\" = '{$this->$value}'";`
and change it to `elseif ($AQ->multiple) $notDeletedFK[$key] = "$key = '{$this->$value}'";`
or `elseif ($AQ->multiple) $notDeletedFK[$key] = "<<<backtick>>>$key\<<<backtick>>> = '{$this->$value}'";`
replace `<<<backtick>>>` with \`
I hope I could release stable version soon. Please manually fix this line before I release new stable version.

**Comment by medzhidov** [comment]
Thanks!

**Comment by mootensai** [comment]
It should be fixed by `composer update` as i already release new version of yii2-relation-trait
