### ISSUE TITLE
bug in update relational records

### ISSUE THREAD

**Issue by masihfathi** [mootensai/yii2-enhanced-gii#109]
when i want to update a record with relational records it gets error "duplicate entry" i make a column unique but in update a parent record it's get error

**Comment by ednotorres** [comment]
What is th type of your PK? I had the same problem when using autoincrement PK and UUIDBehavior.

**Comment by masihfathi** [comment]
type of pk in the parent table is string and in the relational table is integer(AI)

**Comment by cgernert** [comment]
Hi,

The UUID should be stored in CHAR(32).
My database does not support auto increment for columns other than primary
key, so I added this to my controller:

$taskCount = (new
Query)->select('public_id')->from('task')->max('public_id');
if (isset($taskCount)) {
    $public_id = intval($taskCount) + 1;
} else {
    $public_id = 1;
}

Best
Christoph

**Comment by masihfathi** [comment]
i think the saveall() method have problem, when i want to update relational record in domain detail it can't update:
![screenshot from 2017-05-23 11-15-27 1](https://cloud.githubusercontent.com/assets/13271510/26341908/1a9277bc-3fab-11e7-9c27-c7891cd5ca4d.png)

**Comment by cgernert** [comment]
I'm not 100% sure. seems like your title column is a primary key or at
least an unique index and the same title already exists in the
domain_detail table... probably for another domain.

**Comment by masihfathi** [comment]
the title in the second table is unique and when insert only unique records insert to db so for updating when i want to update same record it should not get error.

**Comment by mootensai** [comment]
Please send me your schema..

**Comment by masihfathi** [comment]
```
<?php
use yii\db\Schema;

class m170520_130100_create_domains_table extends \yii\db\Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_persian_ci ENGINE=InnoDB';
        }
        
        $this->createTable('domains', [
            'domain' => $this->string(40)->notNull(),
            'updated_at' => $this->integer(11)->notNull(),
            'created_at' => $this->integer(11)->notNull(),
            'PRIMARY KEY ([[domain]])',
            ], $tableOptions);
                
    }

    public function down()
    {
        $this->dropTable('domains');
    }
}
?>
```
```
<?php

use yii\db\Schema;

class m170520_130101_create_domain_details_table extends \yii\db\Migration {

    public function up() {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_persian_ci ENGINE=InnoDB';
        }

        $this->createTable('domain_details', [
            'id' => $this->primaryKey(),
            'domain' => $this->string(40)->notNull(),
            'url' => $this->text(),
            'title' => $this->string(255)->notNull(),
            'created_at' => $this->integer(11)->notNull(),
            'updated_at' => $this->integer(11)->notNull(),
            'FOREIGN KEY ([[domain]]) REFERENCES domains ([[domain]]) ON DELETE CASCADE ON UPDATE CASCADE',
                ], $tableOptions);       
        $this->createIndex('index_unique_column', '{{%domain_details}}', 'title', true);
    }

    public function down() {
        $this->dropColumn('{{%domain_details}}', 'url');
        $this->dropTable('domain_details');
    }

}
```

**Comment by mootensai** [comment]
please try again with `composer update` first

**Comment by masihfathi** [comment]
i do `composer update` but the error did not change

**Comment by mootensai** [comment]
I've tested your schema, and it works after i remove UUIDBehavior on children model (domain_details)
![image](https://user-images.githubusercontent.com/5844149/28197428-0f249f5a-6881-11e7-908b-1a4e7fe75b46.png)

**Comment by masihfathi** [comment]
i don't have this uuid behavior in my model, can you plz send me full model or send full blank project with this crud

**Comment by timbreitscheit54** [comment]
I would like to have a complete table for example.
