### ISSUE TITLE
Hello Moo 

### ISSUE THREAD

**Issue by motionland** [mootensai/yii2-enhanced-gii#11]
Just a minor issue ---> 
 line 25
 $relName = ($isHasMany) ? lcfirst($key) . 's' : lcfirst($key);

**Comment by mootensai** [comment]
```
                                                                                  You can view it on the composer.json file
```

**Comment by mootensai** [comment]
Sorry, I dont use skype very much. Why dont use gitter?

**Comment by motionland** [comment]
contacted you via email --- thanks
