### ISSUE TITLE
saveAll() function deletes all related records 

### ISSUE THREAD

**Issue by assafwint** [mootensai/yii2-enhanced-gii#111]
I noticed weird behavior using the saveAll() function with M2M relations.
I have a table called zone (zone_id, zone_name)
and 2 many-to-many relations:
zone_user (zone_id, user_id)
zone_template (zone_id, template_id, zone_template_settings) => can the extra field pose an issue?

When I add a new zone_user record, first I call loadAll() which loads the data fine and then I call saveAll():
Which first goes to delete ALL child records, including DELETE FROM zone_template where zone_id = XX
The issue is, that I didn't update / delete / create a zone_template, I was working with zone_user
and $_POST doesn't even have zone_template data.

First, I don't understand why is it deleting records which I did not try to modify
Second, I get an exception (which is expected) when it tries to delete the zone_template records since it has foreign key constraints to other tables...

It fails on RelationTrait line 226 (using "mootensai/yii2-enhanced-gii": "dev-master") 

Would appreciate your help.
Thanks!

**Comment by ednotorres** [comment]
I think the answers on the issue #105 can help you.

**Comment by mootensai** [comment]
it should be fixed by last version of yii2-relation-trait
