### ISSUE TITLE
Uuid works wrong

### ISSUE THREAD

**Issue by medzhidov** [mootensai/yii2-enhanced-gii#113]
After i creating any element, it will has random number in it's id column, when uuid is turned on.

Dependencies:
"yiisoft/yii2": "~2.0.6",
"mootensai/yii2-enhanced-gii": "dev-master"
"kartik-v/yii2-tree-manager": "dev-master"

**Comment by cgernert** [comment]
... and that's the purpose of an UUID!
https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by medzhidov** [comment]
Hm, but i had trouble when it give number out of maximum in mysql, something like 2147483647.
May be error not in this plugin, but when i turned off this, mistake was fixed.

**Comment by cgernert** [comment]
A UUID is not an integer number. Please use a suitable data type.
https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

If do not know what an UUID is, you probably should not use it.

**Comment by medzhidov** [comment]
Great thanks, and sorry)
