### ISSUE TITLE
Notice when generating models

### ISSUE THREAD

**Issue by cyril-amar** [mootensai/yii2-enhanced-gii#115]
Hi,

I have the following notice when I try to generate all my models with *. It happens before display the screen with the previews.

> Undefined variable: relations

According to the trace, the variable `relations` is used on line 41 of file vendor\mootensai\yii2-enhanced-gii\model\default\query.php

Regards,

**Comment by mootensai** [comment]
Sorry, please try again..
Do `composer update`

**Comment by cyril-amar** [comment]
Wow, that was quick! Thanks.

I now have a syntax error on line 25 (same file):

> syntax error, unexpected '*'

Regards

**Comment by mootensai** [comment]
Please try again.. Sorry, currently I change it via phone. So I cant really check the code

**Comment by cyril-amar** [comment]
Perfect, nice work!

Thanks,

**Comment by ronaldobarrera** [comment]
Generated code has this error on models "php expression is not allowed as field default value"

    private $_rt_softdelete = [
        'deleted_by' => \Yii::$app->user->id,
        'deleted_at' => date('Y-m-d H:i:s'),
    ];
    private $_rt_softrestore = [
        'deleted_by' => 0,

        'deleted_at' => date('Y-m-d H:i:s'),
    ];

**Comment by ronaldobarrera** [comment]
Can you move the assign statement inside the constructor to fix this.

**Comment by mootensai** [comment]
@ronaldobarrera could you explain more with code sample?

_Sent from my ZUK Z2131 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ronaldobarrera** [comment]
It happened after the last commit... The generated code should read something like

    private $_rt_softdelete;

    function __construct() {
    $this->_rt_softdelete = [
        'deleted_by' => \Yii::$app->user->id,
        'deleted_at' => date('Y-m-d H:i:s'),
    ];
    }

**Comment by mootensai** [comment]
Alright!! That's a good idea.. will do.. wait for next commit..

_Sent from my ZUK Z2131 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mootensai** [comment]
Ok, please try again..

**Comment by ronaldobarrera** [comment]
Thanks for the immediate fix!

**Comment by ronaldobarrera** [comment]
You forget to call the parent constructor and to initialize the softDelete behaviour.

        parent::__construct();

**Comment by mootensai** [comment]
Thanks! Please try again..
