### ISSUE TITLE
Wrong namespace generated by CRUD generator for Search model

### ISSUE THREAD

**Issue by realmarkcross** [mootensai/yii2-enhanced-gii#12]
Hi.  Thanks for a GREAT addition to Yii2.  It's a real time saver.

When I create new CRUD for a model, the namespace for the Search model won't change to reflect the namespace that I put into the Gii form.  It always says 'frontend' in the final generated documents, instead of what I put into the form which is 'frontend\models'.  

For example, in the Gii CRUD page, I created a new CRUD model class called 'entity'.  I select 'Generate Search Model' and change the Search Model Namespace to 'frontend\model' which works great for the Model Namespace and the Controller namespace, but in Search model will only generate 'frontend' for the namespace when I generate the classes, even though I've entered 'frontend\models.'

In the interim, can I just use the regular Gii CRUD generator to generate the Search model alone?  Is the Search model code that is generated by the Enhanced Gii Generator the same as the regular Gii Search model?

**Comment by mootensai** [comment]
will be fixed by next update. don't forget to use dev-master version
