### ISSUE TITLE
Error in actionCreate

### ISSUE THREAD

**Issue by pcalafatich** [mootensai/yii2-enhanced-gii#121]
Hi mootensai
 I have an error in ActionCreate in method loadAll (Method app\models\Round::loadAll() does not exist'). Since that loadAll not exists as a YII native method nor a client method I can't resolve that.  Could you give me some help??? Thanks in advance.

**Comment by mootensai** [comment]
did you generate it?

**Comment by pcalafatich** [comment]
Yes. I generate my model/crud/controller with the extension

**Comment by pcalafatich** [comment]
This is the generated code

/**
     * Creates a new Round model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Round();

        if ($model->**loadAll**(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

**Comment by pcalafatich** [comment]
This is the generated code
/**
     * Creates a new Round model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Round();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

**Comment by pcalafatich** [comment]
This is the generated code

`/**
     * Creates a new Round model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Round();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    } `

**Comment by pcalafatich** [comment]
I found that loadAll is a method from yii2-relation-trait extension. I supose that this extension is a dependance but I dont know why not was added. I'm still searching what's wrong here
