### ISSUE TITLE
create / form view not working

### ISSUE THREAD

**Issue by timbreitscheit54** [mootensai/yii2-enhanced-gii#128]
hi mootensai, I was able to complete generation of views for all my tables without any errors. now when i go to urgencies/create ... i receive a 404. I can add urgencies in the three view but i still would like to have the option of the traditional form. Can you please give a hint how to make it work again? create.php and _form.php exist alright

haha never mind. sorry. still learning .found the missing code in the controller. many thanks!

**Comment by kidzen** [comment]
please close the issue if it is solved. and do mind to share your solution for other refference

**Comment by mootensai** [comment]
use gitter to ask, don't create issues..

**Comment by mootensai** [comment]
u better learn to use Yii 2 first before use this extension..
