### ISSUE TITLE
Unknown method deleteWithChildren when attempting to delete record

### ISSUE THREAD

**Issue by realmarkcross** [mootensai/yii2-enhanced-gii#13]
I've created the CRUD for a model and am able to insert, view and update the record, but when I try to delete the record, I get: Calling Unknown Method: frontend\models\Entity::deleteWithChildren()

If I generate the CRUD using the normal Gii generator, there is no error.

**Comment by realmarkcross** [comment]
I have been able to make the Delete function work by replacing the deleteWithChildren() method with deleteWithRelated() method.

**Comment by mootensai** [comment]
OK, will fix it.. Thanks!
