### ISSUE TITLE
Bug - when updating model + model related with dynamic form - duplicated entries on DB

### ISSUE THREAD

**Issue by alvarolordelo** [mootensai/yii2-enhanced-gii#138]
Hi folks,
version:

mootensai/yii2-enhanced-gii | 9999999-dev
mootensai/yii2-jsblock   1.0.0.0
 mootensai/yii2-optimistic-lock-validator 0.0.1.0
mootensai/yii2-relation-trait  1.1.8.0

I'm using the default crud with yii2-enhanced, when I perform update action the model related is being duplicated, what I did to solve it, sent the table related id in the dynamic form with label = ' empty
'id'=>['type' => TabularForm::INPUT_HIDDEN, 'label' => ''],
If not that way after the update the record it gets duplicated on my table.

By default, gii isn't creating the table ID on the dynamic form. I did it manually.
I will put here what it sends before and after I add the id field.
BEFORE
![image](https://user-images.githubusercontent.com/1663952/36848357-c781daa4-1d3f-11e8-85ed-9dcbdbca8a7a.png)

And now after including the id on the dynamic form.
![image](https://user-images.githubusercontent.com/1663952/36848486-1bbf44b2-1d40-11e8-8a58-d97675c82b4a.png)

What I get from the difference between them is that - sending the row ID made the action perform as expected. And stopped the duplicated row on my table.

**Comment by cgernert** [comment]
I also noticed this behaviour. It seems to be a quirk of the Kartik TabularForm.

**Comment by cgernert** [comment]
The saveAll() function needs the id to distinguish between existing and new records. Without id it will not know if the record was already existent in the DB and create a new one.

The id get inserted into the POST only if the TabularForm is configured as you described above
Head over to https://github.com/kartik-v/yii2-builder and see, what info you can get about this behaviour
