### ISSUE TITLE
"Call to a member function getColumnNames() on null" 

### ISSUE THREAD

**Issue by drew1two** [mootensai/yii2-enhanced-gii#160]
Error occurs in _datarefone.php line 15:-
$pk = empty($tableSchema->primaryKey) ? $tableSchema->getColumnNames()[0] : $tableSchema->primaryKey[0];

This is because there is no tableSchema being generated.
Need to change line 14 from :-
$tableSchema = $generator->getDbConnection()->getTableSchema($relations[$generator::REL_CLASS]);
to:-
$tableSchema = $generator->getDbConnection()->getTableSchema($relations[$generator::REL_TABLE]);
getTableSchema takes the tableName, not the className.

And all is good in the world again :)

**Comment by mootensai** [comment]
Hi! Could you make a PR for this? I'm back in WebDev now. I will have time to maintain this repo again.
