### ISSUE TITLE
Edit Generator Code

### ISSUE THREAD

**Issue by leocharrua** [mootensai/yii2-enhanced-gii#168]
Hello, I have custom templates and works ok.
But how I can edit the generators code without overwrite the vendor folder?
Thanks

**Comment by mootensai** [comment]
Sorry, I don't really get what you mean.

**Comment by leocharrua** [comment]
Hello. I need edit the generator source code (\vendor\mootensai\yii2-enhanced-gii\model\Generator.php). Is there any way to copy and edit this, like I do with the templates without edit the original code (in vendor\...)? How I can do that?
Thanks again

**Comment by mootensai** [comment]
no, you can't do that.
