### ISSUE TITLE
Auto increment primary keys fails

### ISSUE THREAD

**Issue by leocharrua** [mootensai/yii2-enhanced-gii#171]
Hello @mootensai !!!

I'm having trouble with the auto_increment primary keys.
For a strange razon, your code calls the UUID logic to assign this fields.

See this link: https://forum.yiiframework.com/t/yii-seems-to-neglect-auto-inrement-for-primarykey/87057/37

Any help?

Thanks

**Comment by mootensai** [comment]
you could disable UUID feature by emptying `UUID Column`.

edit : that column is in Model Generator form

**Comment by mootensai** [comment]
![Screen Shot 2021-06-19 at 05 43 59](https://user-images.githubusercontent.com/5844149/122622044-9dd24200-d0c1-11eb-96c1-0e9c887500dc.png)

**Comment by leocharrua** [comment]
Thanks!!!
