### ISSUE TITLE
Blameable behaviors have wrong default namespace for User

### ISSUE THREAD

**Issue by realmarkcross** [mootensai/yii2-enhanced-gii#20]
When generating models with blameable behaviors on an advanced Yii2 platform, the blameable behaviors incorrectly default to frontend\models namespace but the user models are in common\models by default. 

Some people may move their User models to other namespaces as well other than common\models or frontend\models.  Perhaps an area to specify the namespace for the blameable behaviors would be nice?

**Comment by mootensai** [comment]
Sorry, I don't get it. is Blameable behaviors generating any namespace for user model?

**Comment by realmarkcross** [comment]
When you create a base model with BlameableBehaviors, the base model is created with both the PHPDoc notation as frontend\models\User (which should be common\models\User) as here:
- @property \frontend\models\User $createdBy // <--should be \common\models\User

AND in the method in the base model (same on getUpdatedBy() method too):

 public function getCreatedBy()
    {
        return $this->hasOne(\frontend\models\User::className(), ['id' => 'created_by']); 
    }

**Comment by mootensai** [comment]
It depends on your Model Namespace input.

**Comment by realmarkcross** [comment]
Yes, but User is located in common by default while most other models are located in frontend by default (assuming you're working on the frontend of course.)

**Comment by mootensai** [comment]
I don't think I will fix it, You should manually change the namespace of User to your User location..
