### ISSUE TITLE
Can not install kartik-v/yii2-grid version 3.0.6

### ISSUE THREAD

**Issue by brian3t** [mootensai/yii2-enhanced-gii#25]
Expect: kartik-v/yii2-grid version 3.0.6 installed
Outcome: kartik-v/yii2-grid version 3.0.2 is chosen by composer

Not sure if this is kartik-v extensions issue or mootensai's extension issue.
Should probably set require to @dev instead of '*'

**Comment by mootensai** [comment]
use `mootensai/yii2-enhanced-gii:dev-master` when require will give you the result you expected

EDIT : 
I just understand what you mean, i'll fix it on readme.md file on how to install..

Thanks!
