### ISSUE TITLE
Grid Settings specify Font Awesom in some places 

### ISSUE THREAD

**Issue by sganz** [mootensai/yii2-enhanced-gii#27]
The generated settings for the grids specify Font Awesome in some cases, other case is not specified. Font Awesome is not installed by default (I think).  Kartik-V has the option to use that but it's not part of the composer packaging so for the Export menu's on the index.php page the icons don't show. On pages were a foreign key creates a tabular grid it does not specify Font Awesome so the icons in the export menu show up since they are defaulted to glyph icons.

I added the Kartik icon frame work to my project and that fixed up the index.php page. In view.php I added a couple of lines of code to also use Font Awesome. -

``` php
<?php
    $gridColumnModel = [
        ['class' => 'yii\grid\SerialColumn'],
        ['attribute' => 'id', 'hidden' => true],
        [
            'attribute' => 'fkMake.id',
            'label' => 'Make',
        ],
        'ed_id',
        'model_name',
        'nice_name',
        'year',
        'processed_state',
        'dte_update',
    ];
    echo Gridview::widget([
        'dataProvider' => $providerModel,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
        'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => '<h3 class="panel-title"><i class="glyphicon glyphicon-book"></i>  ' . Html::encode('Model'.' '. $this->title) . ' </h3>',
        ],
        'columns' => $gridColumnModel,

         // Added the export options  here
         'export' => [
            'fontAwesome' => true,
        ],
    ]);
?>


```

In any case I think either add the code to set to use Font Awesome or set default to not use it.

Just started looking at the generator, looks cool.

Sandy

**Comment by mootensai** [comment]
Should I require kartik-v/yii2-icons at my composer?

**Comment by sganz** [comment]
Not sure, but if you the other option is to set the 'fontAwesome' to false and then it doesn't require it by default. Using it is nicer as the menus look better. If you are using Kartik's grids it's not a bad idea to use the icon package as it will be useful for other things too.

**Comment by mootensai** [comment]
Is this still a problem? Maybe I don't really get it what you mean..

**Comment by sganz** [comment]
It's been a while since I looked at it. I think one problem was that the view needed to have font awesome included or icons didn't render. It may have been related to pages that had foreign keys that were used to generate tables, but it's been a while and I can't remember ;)

**Comment by mootensai** [comment]
I'll close it for now. But, if it still happen, feel free to report again. Thanks!!
