### ISSUE TITLE
Add if statement in view

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#29]
In a view view.php the relations are sometime empty and are useless.
Please add an if statement to check if it is empty to skip the block.

```
    if ($providerNameXXX->totalCount > 0) {
          echo Gridview::widget([
          'dataProvider' =>
```

**Comment by mootensai** [comment]
can you give me an example? 
what kind of data structure and how it generates?
and what is `->totalCount` means? 
total row count at database?

**Comment by arjenmeijer** [comment]
Example in view.php:

``` php
    if ($providerGebeurtenis->totalCount > 0) {
       echo Gridview::widget([
              'dataProvider' => $providerGebeurtenis,
              'pjax' => true,
              'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
              'panel' => [
              'type' => GridView::TYPE_PRIMARY,
              'heading' => '<span class="panel-title"><i class="glyphicon glyphicon-bullhorn"></i> </span> ' . Html::encode(Yii::t('3de5', 'Eventtype').' '. $this->title.' '.Yii::t('3de5', 'is being used in')),
              'columns' => $gridColumnGebeurtenis
          ]);
     }
```

->TotalCount is the build in function to count the total number of rows in a dataprovider.

So it is saying: If there is data, show the widget, otherwise skip it.

**Comment by mootensai** [comment]
Hmm.. I think it's a good idea.. will implement it on the next release..

Thanks!!
