### ISSUE TITLE
Error when using kartik\range\RangeInput;

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#30]
If I use 

<?= $form->field($model, 'motiefbestaandoel')->widget(RangeInput::classname(), [
    options' => ['placeholder' => 'Select range ...'],
    'html5Options' => ['min'=>0, 'max'=>100, 'step'=>1],
]); ?>

in a form, I get error:
Invalid Parameter – yii\base\InvalidParamException
app\models\Spelrondeactievegroepen has no relation named "spelrondeactievegroepen-motiefbestaandoel-source".
↵
Caused by: Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\Spelrondeactievegroepen::getspelrondeactievegroepen-motiefbestaandoel-source()

in /var/www/html/pro.3de5.nl/vendor/yiisoft/yii2/base/Component.php at line 285
1. in /var/www/html/pro.3de5.nl/vendor/mootensai/yii2-relation-trait/RelationTrait.php at line 26 – yii\db\BaseActiveRecord::getRelation('spelrondeactievegroepen-motiefbe...')

If I replace the Rangeinput with a normal input field, the form works fine.

Do I have specify something extra when using this ranginput widget?

**Comment by mootensai** [comment]
Have u solved this issue?
I never use RangeInput before. Sorry , I don't know..

**Comment by arjenmeijer** [comment]
No, still getting this error on update or creation:
app\models\Spelronde has no relation named "spelronde-spelrondemaxaantalspelers-source".
with code:

``` javascript

use kartik\widgets\RangeInput;

<?= $form->field($model, 'spelrondemaxaantalspelers')->widget(RangeInput::classname(), [
        'width' => '75%',
        'html5Options' => ['min'=>2, 'max'=>8, 'step'=>1],
        ]);
```

Why is the field 'spelrondemaxaantalspelers' changed in "spelronde-spelrondemaxaantalspelers-source"?
