### ISSUE TITLE
Installation error: kartik-v/yii2-export v1.2.2 requires phpoffice/phpexcel 1.8.0

### ISSUE THREAD

**Issue by AntoninSlejska** [mootensai/yii2-enhanced-gii#31]
When installing the yii2-enhanced-gii I receive the following error. phpoffice/phpexcell is in my application already present in the latest version **1.8.1** (composer.json: "phpoffice/phpexcel": "dev-master").

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - kartik-v/yii2-export v1.2.2 requires phpoffice/phpexcel **1.8.0** -> no matching package found.
>     - kartik-v/yii2-export v1.2.1 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
>     - kartik-v/yii2-export v1.2.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
>     - kartik-v/yii2-export v1.1.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
>     - kartik-v/yii2-export v1.0.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
>     - Installation request for mootensai/yii2-enhanced-gii dev-master -> satisfiable by mootensai/yii2-enhanced-gii[dev-master].
>     - mootensai/yii2-enhanced-gii dev-master requires kartik-v/yii2-export \* -> satisfiable by kartik-v/yii2-export[dev-master, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.2.3].
>     - kartik-v/yii2-export dev-master requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
>     - kartik-v/yii2-export v1.2.3 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
>     - Conclusion: don't install phpoffice/phpexcel 1.8.x-dev
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
> 
> Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by AntoninSlejska** [comment]
The installation was successful after changing the composer.json:
"phpoffice/phpexcel": "**^1.8**",

**Comment by mootensai** [comment]
use `mootensai/yii2-enhanced-gii:dev-master` when require should automatically solve that.
