### ISSUE TITLE
Request for view and update details

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#33]
You added the details view to the generator. Very nice.

To make this even better I am trying to implement the view and edit screens in a detail view. I have it more or less working. But not everything is working fine: Errors are not shown in the details view, the submit button in not enabled/disabled and after an update the key is lost.

Are you interested to add this feature as well. I can send you my code.

**Comment by mootensai** [comment]
Well, maybe that will look good.
Please try my new update and add this on grid column

```
        [
            'class' => 'yii\grid\ActionColumn',
        ],
```

![detail action button](https://cloud.githubusercontent.com/assets/5844149/13100500/3df1c83a-d570-11e5-88c1-2db1454c43d8.PNG)

I'll try to improve that today

This is what you mean right?.

**Comment by mootensai** [comment]
done by last update, please use dev release for a while

**Comment by mootensai** [comment]
Totally done, please update
