### ISSUE TITLE
['id' => 'kv-pjax-container']] => id should be unique on a page.

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#36]
Example generated code:
        echo Gridview::widget([
            'dataProvider' => $providerX,
            'pjax' => true,
            'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
            'panel' => [ ...
The generated id is always «kv-pajax-container» in a view file even if there multiple containers.
Make the id unique: add a number of name to it.

**Comment by mootensai** [comment]
Which file is it?

**Comment by mootensai** [comment]
Thanks!
