### ISSUE TITLE
Export buttons twice in index

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#37]
In an index.php the export buttons appears twice in the latest code: Page and Full.

'{toggleData}', is missing.

**Comment by mootensai** [comment]
export buttons is always generated twice, 
page is for exporting only the page you are viewing, (ex : page 1 only)
Full is for exporting all the data that the table have (ex : export 500 row data)

where is the '{toggleData}'?

**Comment by arjenmeijer** [comment]
It the previous version exporting the page or all, was triggered with {toggleData} All - Page. This changed the view as well. This previous version is the way to go in my opinion.

**Comment by mootensai** [comment]
Hmm... Maybe it's because of the detail view options. 
Have you tried without checking the "Expandable Index Grid View" check box?

**Comment by arjenmeijer** [comment]
I will try it later this week.

**Comment by mootensai** [comment]
Hi, have u try it again?

**Comment by arjenmeijer** [comment]
In the latest dev version I get:
a. Page: Export page data html to json 6 items
b. Full: Export all data  html to Excel2007 6 items, 3 the same, tree different 

Mmm, a better version is, I think:
a. Choose a page or all data.
b. Export to a format.

**Comment by mootensai** [comment]
Hi! 
Is this issue still happening? I tested it and it works fine, even after generated detail view..

**Comment by arjenmeijer** [comment]
I will not be able to test it right away. So see it as fixed.
