### ISSUE TITLE
tabel prefix?

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#38]
I am using a prefix in my table names: tbl_.
I do not use the Yii2 prefix, but this does not matter.
I generate class names without tbl_ as is recommended.

This setup is not possible in enchanced-gii. The code generated always gives classes the tbl prefx name.
Is it possible to give the table name a prefix, but the class names no prefix?

**Comment by mootensai** [comment]
Do you use . (dot), at the end of your prefix? -> ex : tbl_.persons

How about the generated model with check on 'use table prefix'? 

maybe the generated CRUD is not support prefix yet, i'll test that..

**Comment by arjenmeijer** [comment]
If I use tbl prefix the generator only uses it for the master table, not for the relations. Hence, the class names have tbl in the name.

I do not use a dot in the name.

**Comment by mootensai** [comment]
Thanks!

**Comment by mootensai** [comment]
Hi! Have you tried the new version with table prefix?

**Comment by arjenmeijer** [comment]
I will do it in the afternoon.
