### ISSUE TITLE
Request: Use Growl message after generation of code

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#4]
The generation screen is large, so it is impossible to see if a generation is successful without scrolling.
Make the message a growl message and the problem is solved.

use kartik\widgets\Growl;

echo Growl::widget([
    'type' => Growl::TYPE_SUCCESS,
    'title' => 'Succes',
    'icon' => 'glyphicon glyphicon-ok-sign',
    'body' => 'Generation of xxxx was succesful.',
    'showSeparator' => true,
    'delay' => 0,  // wait time
    'pluginOptions' => [
        'showProgressbar' => false,
        'delay' => 5000,    // time on screen
        'placement' => [
            'from' => 'top',
            'align' => 'right',
        ]
    ]
]);

**Comment by mootensai** [comment]
I can't do that, if i want to do that, i have to create my own module. I can't access the gii controller's code.
