### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#40]
The _form.php code is generated in each setup. That implies that if I change a field, I have to change it in a lot of places. That is hardly doable if the code grows.

Moreover, the views are manually tweaked with bootstrap columns. Like

```
        <div class="row">
            <div class="col-sm-6">
            <?= $form->field($model, 'namefield')->textInput() ?>
            </div>
```

or in an index view columns are not displayed.

Is it possible to reuse  the original form code (by including this code).

**Comment by mootensai** [comment]
Sorry, I don't really get what you mean..

**Comment by arjenmeijer** [comment]
Each table has its own index.php and _form.php. 
Generating the details view in an other file with a relation to the first table makes a new formNamex.php with is almost, but not completely, the same as the index.php.

Maintaining this code is almost impossible if you use many relations. A change in one field name  requires you to change the filed name in all related models.

It would be great if the field names - the columns -  can be reused. Make this optional.

**Comment by mootensai** [comment]
Hmm.. It will be quite complex do that.. 

Let me think about it. Do you have idea on how to make that happen?

**Comment by arjenmeijer** [comment]
The goal is to code everything just once. 

All the view files have the same structure:
1.  Setting the title and buttons, depending on update, view, create
2.  Displaying the data in 3 forms:
     a. index views, rows of data horizontal
     b. _forms, one row of data, free format
     c. list views, one row of data vertical

Make a subfolder for the display fields and put the 3 forms in it. Copy from there by including this files.
Only link to original table subfolder, not that of a relation.

Moreover, make a 'mother' version of the buttons in the lay out folder and link to it.

In this way, if you change a field or form, it is changed everywhere.

**Comment by mootensai** [comment]
After I check the code of each file, it contains a lot of different code. every file have different columns because different relation have different fields.. 

if the file generated is prefixed with '_' it means it rendered by 'mother' file already..
