### ISSUE TITLE
error after upgrading yii2-relation-trait 1.0.8

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#41]
`[22-Feb-2016 15:43:18 Asia/Jakarta] PHP Fatal error:  Can't use function return value in write context in /home/k2681793/public_html/demo002/vendor/mootensai/yii2-relation-trait/RelationTrait.php on line 39`

How to solve this error? Thanks

**Comment by mootensai** [comment]
could you give me the relation of the tables?

if i checked on line 39 at RelationTrait.php it's just 

```
if (!empty(array_filter($relPost))) 
```

not returning anything

**Comment by mootensai** [comment]
How to reproduce the error?

**Comment by mootensai** [comment]
If i googled around, it's because your PHP is below 5.5, please upgrade your PHP version

**Comment by mootensai** [comment]
or upgrade to dev version, i've fixed the bug

**Comment by mootensai** [comment]
Thanks!
