### ISSUE TITLE
Data can't be deleted because it's still used by another data

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#43]
I'm using 0.0.8, I got this error when I was trying to create/submit 1 data. 

![1](https://cloud.githubusercontent.com/assets/3026828/13273409/d3b4080a-dad5-11e5-9871-2e6bd7c9bafc.PNG)

This is the error after I clicked "Create" button: 

![2](https://cloud.githubusercontent.com/assets/3026828/13273412/de462e2e-dad5-11e5-90b1-2f92615fa0d0.PNG)

**Comment by mootensai** [comment]
could you give me the SQL related to that table?

**Comment by RGTimothy** [comment]
```
CREATE TABLE IF NOT EXISTS `sales_key_focus_plan` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` int(11) NOT NULL COMMENT 'Sales Name',
  `date_from` date NOT NULL COMMENT 'From',
  `date_to` date NOT NULL COMMENT 'To',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `FK_sales_key_focus_plan_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `sales_key_focus_plan_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `sales_key_focus_plan_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Focus Plan ID',
  `customer` varchar(100) NOT NULL COMMENT 'Customer',
  `objective` text NOT NULL COMMENT 'Objectives',
  `appointment_datetime` datetime DEFAULT NULL COMMENT 'Appointment Date/Time',
  `remarks` text COMMENT 'Remarks',
  PRIMARY KEY (`id`),
  KEY `sales_key_focus_plan_id` (`sales_key_focus_plan_id`),
  CONSTRAINT `FK_sales_key_focus_plan_detail_sales_key_focus_plan` FOREIGN KEY (`sales_key_focus_plan_id`) REFERENCES `sales_key_focus_plan` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

**Comment by mootensai** [comment]
does the table `sales_key_focus_plan_detail` is related to another table?

**Comment by RGTimothy** [comment]
No, its not. That table just has 1 foreign key (sales_key_focus_plan_id) with its reference table : "sales_key_focus_plan.id"

**Comment by mootensai** [comment]
OK, the problem is on mootensai/yii2-relation-trait

I've fix that bug, please try to update & use the dev version

i don't know if this works
`
composer update mootensai/yii2-relation-trait:@dev
`
if it don't work, then 

```
composer remove mootensai/yii2-relation-trait

composer require mootensai/yii2-relation-trait:@dev
```

**Comment by RGTimothy** [comment]
Do I have to regenerate the CRUD with enhanced-gii?

**Comment by mootensai** [comment]
No, you don't have to

**Comment by RGTimothy** [comment]
Splendid! Its working now. Thanks.
