### ISSUE TITLE
Request for details tab

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#46]
Thank you for making the details visible in an index view. That is really wonderful.

It would be even better if the first tab would be a detail view of selected line. Most files I user are to large to view in one index line. So I display only the most important fields. It would be wonderful to see the details in a tab without using the view button. Just like the relations.

**Comment by mootensai** [comment]
I think that's a good idea & I can do that. Will do at next release! :grinning:
