### ISSUE TITLE
Some informatie over One-page-CRUD template requested

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#47]
In a _form.php file you generate for example:

```
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'Classname', 
        'relID' => 'clasname', 
        'value' => \yii\helpers\Json::encode($model->classnames),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
```

and 

```
 <div class="form-group" id="add-classname"></div>`
```

This are preparation to make a one-page-crud? What is the purpose? Can I use it yet by hand?

**Comment by mootensai** [comment]
No, it's not preparation to make a one-page-crud. that's for managing the related form.

one page crud will have to create a new template

**Comment by mootensai** [comment]
you could just ask at 
https://gitter.im/mootensai/yii2-enhanced-gii

**Comment by arjenmeijer** [comment]
Thanks. I did not know gitter.
