### ISSUE TITLE
array_filter() expects parameter 1 to be array, string given

### ISSUE THREAD

**Issue by RGTimothy** [mootensai/yii2-enhanced-gii#48]
There is an error when creating a data with form and secondary form (relation table form). 

![damn2](https://cloud.githubusercontent.com/assets/3026828/13315769/5fbd0cca-dbdf-11e5-8def-6a7935e5e78f.PNG)

![damn](https://cloud.githubusercontent.com/assets/3026828/13315661/ab3d41b6-dbde-11e5-9f77-5972b9c174fa.PNG)

**Comment by mootensai** [comment]
could you show me 
`print_r(Yii::$app->request->post()`

**Comment by RGTimothy** [comment]
where do I have to put that code?

**Comment by mootensai** [comment]
at controller, example

```
public function actionCreate()
    {

        print_r(Yii::$app->request->post());
        return $this->render('create', [
            'model' => $model,
        ]);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
//            return $this->redirect(['view', 'id' => $model->customer_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
```

UPDATE 
if you want to see the
$model->loadAll should still executed if you want to reproduce the error

**Comment by RGTimothy** [comment]
The result is displaying "Array()" for a second and then loading the create view.

**Comment by mootensai** [comment]
please try to reproduce the error..

**Comment by RGTimothy** [comment]
But when i put the code in this function:

<pre>public function actionAddTableB()
    {
        print_r(Yii::$app->request->post());
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('TableB');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('action') == 'load' && empty($row)) || Yii::$app->request->post('action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formTableB', ['row' => $row]);
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
    }</pre>

the result is "Array ( [action] => load [isNewRecord] => 1 ) "

**Comment by mootensai** [comment]
don't `print_r()` on actionAddTableB(), but on `actionCreate()` or `actionUpdate()`

I want to see what you're posting that produce the error

**Comment by RGTimothy** [comment]
Nothing's happens but "Array()"

**Comment by mootensai** [comment]
show me your code at your action

**Comment by RGTimothy** [comment]
<pre>
public function actionCreate()
    {
        print_r(Yii::$app->request->post());
        $model = new TableA();
        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
</pre>

**Comment by mootensai** [comment]
comment `return $this->redirect(['view', 'id' => $model->id]);`

and send me the screenshot of the output

**Comment by mootensai** [comment]
After I checked it, `$relPost` is always array. Maybe the problem is on your form or your database structure.

**Comment by RGTimothy** [comment]
Have you try it by yourself with 2 tables which have the relation I explained before? Because I didnt do any changes to the form after generate it through yii2-enhanced-gii. And there is no problem with the db structure, I think. Just same as my previous explanation.

**Comment by mootensai** [comment]
Yes.. i've tried it.. please show the sql dump here

**Comment by RGTimothy** [comment]
<pre>
CREATE TABLE IF NOT EXISTS `table_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
INSERT INTO `table_a` (`id`, `description`) VALUES
    (2, 'test a'),
    (3, 'desc2');
CREATE TABLE IF NOT EXISTS `table_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `table_a_id` int(11) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  KEY `table_a_id` (`table_a_id`),
  CONSTRAINT `FK_table_b_table_a` FOREIGN KEY (`table_a_id`) REFERENCES `table_a` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
INSERT INTO `table_b` (`id`, `table_a_id`, `description`) VALUES
    (2, 2, 'test b');
</pre>

**Comment by mootensai** [comment]
Thanks! I didn't notice about that. I wonder why did it working all this time.. please try again with @dev version

**Comment by RGTimothy** [comment]
You're welcome. Will try it later. Thanks.
