### ISSUE TITLE
How to regenerate _data.php ?

### ISSUE THREAD

**Issue by kikoucalou** [mootensai/yii2-enhanced-gii#49]
I am not a programmer

I get this error : Invalid Parameter – yii\base\InvalidParamException The view file does not exist ....\views\escale_data.php

I deleded views folder escale, escale models file and escale controllers file to generate news
"_data.php" seems to be generated one time but not regenerated when new generate are done...

Could you tell me how to regenerate "_data.php" ?

**Comment by mootensai** [comment]
```
                                                                                  When u re-generate using enhanced gii, there's some check box upper right the table. U might want to check that (create, overwrite, unchanged)
```

**Comment by mootensai** [comment]
```
                                                                                  And don't forget to check expandable index check box
```

**Comment by kikoucalou** [comment]
I used enhanced gii to re-generate with expandable index check box checked, 

ex : Generating code using template ....\pascal\advanced\vendor\mootensai\yii2-enhanced-gii\crud/default"
skipped models\EscaleSearch.php
overwrote controllers\EscaleController.php
skipped views\escale_form.php
skipped views\escale_pdf.php
skipped views\escale_script.php
skipped views\escale_search.php
skipped views\escale\create.php
skipped views\escale\index.php
skipped views\escale\update.php
skipped views\escale\view.php
done!

As file "_data.php" was previously one time generated and deleted, Now when updsate for some change,  _data.php file is not generated or re-generated,

**Comment by mootensai** [comment]
```
                                                                                  You need to check the 'expandable' check box *I forgot the label*
```

**Comment by kikoucalou** [comment]
Expendable check box  "  Expandable Index Grid View " is well checked, but _date.php file does not appear when preview

**Comment by mootensai** [comment]
Strange... I've test it on my local and it's fine.. which version are you using? Is it @dev version?

**Comment by kikoucalou** [comment]
"mootensai/yii2-enhanced-gii": "@dev",

**Comment by mootensai** [comment]
Hmm.. I tried and it always generate _data.php file.. the file should be _data.php, and _dataRelated.php only.. there's no related_data.php

Maybe you need to create a new project.

If you want to ask anything, use https://gitter.im/mootensai/yii2-enhanced-gii

**Comment by mootensai** [comment]
I'm not sure this is an issue yet, so I'll close this for now till we're sure this is an issue.

We'll continue this at https://gitter.im/mootensai/yii2-enhanced-gii
