### ISSUE TITLE
kartik\Datecontrol instead of kartik\Datepicker

### ISSUE THREAD

**Issue by iurijacob** [mootensai/yii2-enhanced-gii#51]
This is more a suggestion, discard it if you prefer. I think it would be interesting to use kartik\Datecontrol instead of kartik\Datepicker for date fields. It´s far more generic and indeed you still can use datepicker within it.

By the way, thank you. Your extension rocks!

**Comment by almirb** [comment]
I think the same!

**Comment by mootensai** [comment]
It will add more configuration on the config if I use that widget. Will it be confusing for starter?

**Comment by iurijacob** [comment]
Probably yes, but not much more than DatePicker. In my opinion, of course.
