### ISSUE TITLE
Do not use relations in the _detail.php view

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#52]
In the view  _detail.php the generators writes for example, where «rollen» is a relation:
`[
           'attribute' => 'rollen.rol_id',
           'label' => Yii::t('app', 'Rol'),
        ],`

This give a error: Getting unknown property: app\models\Functieinorganisatie::rollen

The error is that the generator  made a relation:

```
    public function getRol()
    {
        return $this->hasOne(\app\models\Rollen::className(), ['rol_id' => 'rol_id']);
    }
```

Not getRol**len**(). I do not know why this happens.

Likewise, In view.php 

```
          [
                'attribute' => 'functieinorganisatie.functie_id',
                'label' => Yii::t('3de5', 'Functie')
        ],
```

gives the same error in a subview of a table. The view itself is functieinorganisatie. So one way or another it is calling itself. Mmmm.

**Comment by mootensai** [comment]
could you give me your sqldump?

It maybe because of your language on your table. The Inflector::pluralize() function cannot pluralize on your language

**Comment by mootensai** [comment]
Does anyone having the same issue in English?

**Comment by mootensai** [comment]
I think this is a language issue. I'll close this until there's another person have the same issue
