### ISSUE TITLE
Add add-name class to accesControl behavior

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#54]
If  a users checks the option: «Logged User Only» (Rename it to Logged in Uses Only) the generator has to add
add-nameclasses to the allowed rules.

`'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update','delete', 'add missing controller actions add-nametable],
                        'roles' => ['moderator', 'admin']
                    ],`

Otherwise, the extra table views in the create and edit forms will not show.

**Comment by mootensai** [comment]
Oh yes, right.. I forgot to add that. 

Will fix it soon

**Comment by arjenmeijer** [comment]
Thanks!
