### ISSUE TITLE
Duplicated code try 2

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#55]
Problem: add one field to a table with six relations.

Required actions: Or generate the complete model again (no option for me) or add the field to the table and generate only the changed table again. But the problem is that I have add the new field to all six relation models because each table has its own _dataNametable.php and formNametable.php in the view of the related table.

Solution: Place _dataNametable.php and formNametable.php once in a subdirectory of view of the table. Refer in all relations only to these files. 

Benefits: No code duplication, changes in just one place, easier to find bugs, ...

**Comment by mootensai** [comment]
Could you give me an example file tree for what you want? I think it will make the form is not flexible. But maybe i'm not understand it enough..

**Comment by mootensai** [comment]
I don't know if I can do what you want. Because it seems impossible, because everything is depends on the app goals. If I generate to single template, it will not be flexible. Maybe to get what you want, you have to build your own template. 
Or maybe, I just not really understand what you suggest..

Thank you

**Comment by arjenmeijer** [comment]
There are two solutions to write reusable code:
a. use classes like Humhub: extend the default classes by adding your own code and use the new classes as start point. This way repeated code is not needed. The newly created class has the code once.
b. use a generator like this one. The code is generated every time over and over again.

I prefer a combination of both. Make new classes for the generator and build from that. This eliminates double code and uses the generator for the unique parameters.

**Comment by mootensai** [comment]
If you want the generator to generate from your base model, you can change the base model at form to your defined model..
1. create a Model class file that extends from yii\db\ActiveRecord
2. change the base model class to your created Model when you use IO Model generator
   ![capture](https://cloud.githubusercontent.com/assets/5844149/16186102/c5f50344-36f2-11e6-9582-69e937de815c.JPG)

then all your models are inherited from 1 base model so the generator is already combination of both your solution
