### ISSUE TITLE
Skip related table data

### ISSUE THREAD

**Issue by almirb** [mootensai/yii2-enhanced-gii#56]
Hi!

In the crud generator form, I would like do have an option do skip the creation of all related table data.   Maybe putting an \* in the "Skipped Relations" field.  What do you think?

Thanks!

**Comment by mootensai** [comment]
Hi! I've thought about that from the start, but it's quite hard when I first build this because I haven't find a way to get all the relation names. Now I've found it. It may be possible. I'll do this when I have time.

Thanks for your suggestion.

**Comment by mootensai** [comment]
As you can see here 

https://github.com/mootensai/yii2-enhanced-gii/blob/master/crud/Generator.php#L70
