### ISSUE TITLE
Request. Make delete withRelated on option

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#57]
If I delete a row in a table all referenced tables rows are deleted as well.

Sometimes this not the desired action, as I found out the hard way.

Please add an option to ask if the user wants to delete only the table row or all related data.

**Comment by mootensai** [comment]
if you don't delete the children, that will be a junk data.

**Comment by moysoft** [comment]
When I updated the master record, the child record on all related tables is soft deleted.
