### ISSUE TITLE
How can I specify a new template?

### ISSUE THREAD

**Issue by devleaks** [mootensai/yii2-enhanced-gii#59]
I struggle a bit to add a new template.
I tried to add this entry in my app config with no luck:

```
    $config['modules']['gii']['generators'] = [
        'enhanced-gii-model' => [
            'class' => 'mootensai\enhancedgii\model\Generator',
            'templates' => [
                'mytemplates' => '@common/gii-templates/model',
            ],
        ],
    ];
```

It works for other generator I use, but not this one. Why? Is it because of the loading in bootstrap?

**Comment by mootensai** [comment]
Yes, it's on bootstrap, you might need to modify bootstrap file

**Comment by mootensai** [comment]
if you want to ask, ask at gitter. you can find the link on readme
