### ISSUE TITLE
The IO CRUD and MODEL isn't working properly

### ISSUE THREAD

**Issue by alvarolordelo** [mootensai/yii2-enhanced-gii#62]
I've been figuring out what is happening when I do generate the model, and then the crud and the create action pull and uncompleted form, like for a small table it is fine, but when the table get bigger the second relation isn't working... there is only the first fom, and no gridview itself.
![image](https://cloud.githubusercontent.com/assets/1663952/15714326/7d8a0f7a-27f0-11e6-9cf6-3f57e15169d8.png)

and the create action to fill the both tables..isn't working.. I checked the code.._FORM_TABLE2 ..seems all right but nothing works!

![image](https://cloud.githubusercontent.com/assets/1663952/15714402/c2436120-27f0-11e6-961b-9029ffc583df.png)

**Comment by mootensai** [comment]
Could you send me your schema?

**Comment by alvarolordelo** [comment]
Of course, btw, sorry for reply late.
I've tried many ways to achieve but no good guess about it...
If you need any information please tell me...
I've notice that when a table has 3 relations it also doesn't work out.
Regards,

2016-06-08 7:49 GMT-03:00 Yohanes Candrajaya notifications@github.com:

> Could you send me your schema?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mootensai/yii2-enhanced-gii/issues/62#issuecomment-224554658,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABlj0G4MatgU5dPBd1_VB2k7dsQ_lLZyks5qJp5IgaJpZM4IrpXk
> .

## 

Álvaro Lordêlo Júnior.

M.Sc. Candidate in Computer Science
UFBA - Salvador, BA, Brazil
Analyst of Systems
UNEB - Alagoinhas, BA, Brazil
Mestrando em Ciência da Computação -UFBA
Bacharel em Análise de Sistemas - UNEB
Analista de Sistemas - www.Ictios.org http://www.ictios.org/
Contato:(71) 9288 9400 - (71) 9915 9400

_UFBA - Universidade Federal da Bahiawww.ufba.br http://www.ufba.br/_
*UNEB *- Universidade do Estado da Bahia
www.uneb.br

**Comment by mootensai** [comment]
please send me your mysql dump to my email if it's so big. Or you could comment on this thread if it's OK with you..

**Comment by alvarolordelo** [comment]
what's your e-mail ? would you provide it ?
isn't that big..22kb

2016-06-08 23:25 GMT-03:00 Yohanes Candrajaya notifications@github.com:

> please send me your mysql dump to my email if it's so big. Or you could
> comment on this thread if it's OK with you..
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mootensai/yii2-enhanced-gii/issues/62#issuecomment-224785073,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABlj0C9KnoY4fSnl_gVTnmtpBdhxrLLPks5qJ3mBgaJpZM4IrpXk
> .

## 

Álvaro Lordêlo Júnior.

M.Sc. Candidate in Computer Science
UFBA - Salvador, BA, Brazil
Analyst of Systems
UNEB - Alagoinhas, BA, Brazil
Mestrando em Ciência da Computação -UFBA
Bacharel em Análise de Sistemas - UNEB
Analista de Sistemas - www.Ictios.org http://www.ictios.org/
Contato:(71) 9288 9400 - (71) 9915 9400

_UFBA - Universidade Federal da Bahiawww.ufba.br http://www.ufba.br/_
*UNEB *- Universidade do Estado da Bahia
www.uneb.br

**Comment by mootensai** [comment]
Then maybe you could paste it here..

**Comment by alvarolordelo** [comment]
please send me your email.. I couldn't add the file..some issue with github

**Comment by mootensai** [comment]
Just paste the text content of the file. You could get my email on composer.json. If I write my email here, I could get spammed..

**Comment by alvarolordelo** [comment]
check your email, please..I've forwarded

**Comment by alvarolordelo** [comment]
Hi guys,
the bug still happening I just did a small change on the table, and the
problem came again...

2016-06-09 2:10 GMT-03:00 Yohanes Candrajaya notifications@github.com:

> Closed #62 https://github.com/mootensai/yii2-enhanced-gii/issues/62 via
> 24392b1
> https://github.com/mootensai/yii2-enhanced-gii/commit/24392b185787727bcc459fbab96de0b7b0950aba
> .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mootensai/yii2-enhanced-gii/issues/62#event-686789297,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABlj0PUnMwL59v2FYTPKXRbMojH-YXPKks5qJ6A3gaJpZM4IrpXk
> .

## 

Álvaro Lordêlo Júnior.

M.Sc. Candidate in Computer Science
UFBA - Salvador, BA, Brazil
Analyst of Systems
UNEB - Alagoinhas, BA, Brazil
Mestrando em Ciência da Computação -UFBA
Bacharel em Análise de Sistemas - UNEB
Analista de Sistemas - www.Ictios.org http://www.ictios.org/
Contato:(71) 9288 9400 - (71) 9915 9400

_UFBA - Universidade Federal da Bahiawww.ufba.br http://www.ufba.br/_
*UNEB *- Universidade do Estado da Bahia
www.uneb.br

**Comment by mootensai** [comment]
What are the changes?

**Comment by alvarolordelo** [comment]
Hi sir, I've sent it by email.

**Comment by mootensai** [comment]
[image: Inline image 1]

I don't understand what it means
