### ISSUE TITLE
What do you guys think about tabbing related form?

### ISSUE THREAD

**Issue by mootensai** [mootensai/yii2-enhanced-gii#67]
![image](https://cloud.githubusercontent.com/assets/5844149/16047008/9d55ee72-3278-11e6-8a2c-debe90b695a1.png)

What do you guys think about it? Test 1, Test 2, Test 3 is the related form.

I tried to remove the heading of the tabular form, but if I add 1 row, it still show the summary ("Showing x data of y data")

**Comment by mootensai** [comment]
next version 
![image](https://cloud.githubusercontent.com/assets/5844149/16066288/299ef154-32dc-11e6-9825-c60cc88535b8.png)

what do you think?

**Comment by marena** [comment]
It looks great :o)

**Comment by mootensai** [comment]
```
                                                                                  Please try & update! It's done! Run'composer require mootensai/yii2-enhanced-gii:dev-master'It support hasOne & belongsTo relation too..:smile:                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the 3 Indonesia network.
```

**Comment by marena** [comment]
Ok, i`ll try.
