### ISSUE TITLE
PostgreSQL schema CRUD Generator Errors

### ISSUE THREAD

**Issue by chitwarnold** [mootensai/yii2-enhanced-gii#70]
Been using this Extension for a while and it seems that your recent updates for the last one month, have really  handicapped Users of PostgresSQL, this the issues i get is with when Generating CRUD, i mean it used to Generate code such as this

```
public function getCommy.messagesReplies()
{
    return $this->hasMany(\backend\modules\commy\models\Comm.messagesReplies::className(), ['child_message_code' => 'message_code']);
}
```

which was ok since it meant just removing the periods, but now the entire generation fails with the error : **syntax error, unexpected '.', expecting '('**

**Comment by mootensai** [comment]
Could you send me your schema?

**Comment by mootensai** [comment]
Is that 'Comm' a table prefix?

**Comment by chitwarnold** [comment]
sorry for the delayed response. yes comm is the schema name, and the messages_replies is the name of the table. Find below the schema table sql

**Comment by chitwarnold** [comment]
```
CREATE TABLE comm.messages_replies (
    id_messages_replies integer NOT NULL,
    parent_message_code uuid,
    child_message_code uuid,
    status integer NOT NULL,
);

CREATE TABLE comm.messages (
    id_messages integer NOT NULL,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    subject character varying(255) NOT NULL,
    message_body text NOT NULL,
    message_tags text NOT NULL,
    message_type integer NOT NULL,
    send_as_sms integer NOT NULL,
    send_as_email integer NOT NULL,
    status integer NOT NULL,
);
```

is the sql for the tables,  they are implemented in the schema named "comm" so typically calling for a table name from gii would be like "comm.messages", the model are created successfully with the few periods implemented inline the code, which is usually just as easy are removing periods and renaming the string. Thereafter the CRUD , previously it used to work without a hitch, now it is not proceeding.

**Comment by khvalov** [comment]
also problem with Postgres 
Getting unknown property: mootensai\enhancedgii\model\Generator::useSchemaName

**Comment by mootensai** [comment]
Could anyone help me about this issue? I'm afraid that this issue is happen on yiisoft/yii2-gii also. Because I extend from that repo.

**Comment by sam002** [comment]
**Doesn't require fix.**
This is a problem of yii2 db connection. Need support for [default schemes](http://www.yiiframework.com/doc-2.0/yii-db-pgsql-schema.html#$defaultSchema-detail) in connection.
See the [solution here](http://stackoverflow.com/questions/26436024/how-to-set-default-schema-in-yii2).
If you have multiple schemes, it should be used foreach individual connection _(the approach I have met on all projects with several schemes)_.

**Comment by mootensai** [comment]
I'll close this issue then... thanks a lot @sam002 !!
