### ISSUE TITLE
Debug Tool bar Logo Rendered in PDF

### ISSUE THREAD

**Issue by gogl92** [mootensai/yii2-enhanced-gii#71]
[DebugToolBar.pdf](https://github.com/mootensai/yii2-enhanced-gii/files/340179/DebugToolBar.pdf)
![debugtoolbar](https://cloud.githubusercontent.com/assets/1505641/16468306/dccf23c2-3e10-11e6-84d4-db76b558488f.png)

The debug Tool Bar is rendered in the PDF. 
This shouldn't be in the PDF even in debug mode.

**Comment by mootensai** [comment]
Any idea on how to remove that?

**Comment by gogl92** [comment]
I will check the code to see what is happening, does anybody had this problem before?

**Comment by mootensai** [comment]
```
                                                                                  I think everybody having the same problem. I have that too, but I think that's OK because it's on debug mode. It will be gone if it's on production mode.
```

**Comment by mootensai** [comment]
@gogl92 have you found any solution to this?

**Comment by gogl92** [comment]
I didn't find a solution there is the option to take the string content and remove all the code of the tool bar but I think that is a good option.

**Comment by mootensai** [comment]
I'll close this issue as this is not a problem at production mode.
