### ISSUE TITLE
Lock Error

### ISSUE THREAD

**Issue by Wamae** [mootensai/yii2-enhanced-gii#73]
I keep getting this error Getting unknown property: app\models\Salaries::lock, when i try to add something to table.
I have no Idea why. 
Please help if possible.

**Comment by mootensai** [comment]
Do you have `lock` column on your tables?? 
If you don't want to use Optimistic Lock feature, then leave optimistic lock option to empty..
If you want to ask anything, please use this

https://gitter.im/mootensai/yii2-enhanced-gii

**Comment by mootensai** [comment]
I'll close this in assumption that you don't have `lock` column

If it still happen, please tell me..

**Comment by bitsnaps** [comment]
@mootensai  This is weird! MySQL doesn't allow to name a field `lock` it's a reserved word!
