### ISSUE TITLE
PHP Notice with related models

### ISSUE THREAD

**Issue by Rinkana190** [mootensai/yii2-enhanced-gii#74]
Hi, thanks for extension!

I've 3 models 
The first one is model where i'am trying to update records. Another two models it is just a dictionaries.
Two more models it is manyToManyRelation models and i have an error in update first model with records from another, because in 
`vendor/mootensai/yii2-relation-trait/RelationTrait.php` at 127 line started a filling of related model keys(it is ok for one) but when there is 2 or more related models keys does not clean and 146 line give to me `PHP Notice – yii\base\ErrorException` with undefined key from another model, it is treated with 
`$fields = [];` at 127 line.

Thanks for the great extension one more time.

**Comment by mootensai** [comment]
is it the same project as you gave me your schema?
if it is, which table is it?
