### ISSUE TITLE
Does not update fields in relatoin model

### ISSUE THREAD

**Issue by Rinkana190** [mootensai/yii2-enhanced-gii#75]
Hi.

I have a date field at ManyToMany relation model, it is filled, when record created, but when i try to update it doesn't updated. Thanks.

**Comment by mootensai** [comment]
Can u send me your schema?

**Comment by Rinkana190** [comment]
http://pastebin.com/e8uhnq6c

**Comment by Rinkana190** [comment]
I created basic crud with your extension and then i tried to create `carta-pacienta/create` and it was done fine. `zabolevaniya_o_has_carta_pacienta`  created a record with correct date, but when i tried to update this field again it didn't udpate.

**Comment by mootensai** [comment]
ok, I'll check as soon as I possible..
Thanks for your report!

**Comment by mootensai** [comment]
I've tried and got no problem on my schema/db.. have you tried to run `composer update` ? Because there's update in mootensai/yii2-relation-trait about datecontrol issues

https://github.com/mootensai/yii2-relation-trait/issues/19

please try again
