### ISSUE TITLE
related don't get deleted

### ISSUE THREAD

**Issue by drew1two** [mootensai/yii2-enhanced-gii#77]
Would appear that when updating a parent model and you 'remove' related, they don't get deleted when updating that parent model.

**Comment by drew1two** [comment]
Only happens when trying to delete the 'last' record.

**Comment by mootensai** [comment]
```
                                                                                  Did you downloaded the dev-master version? It already happen before and i've fixed it already..
```

**Comment by drew1two** [comment]
haven't updated for about a month
sorry
