### ISSUE TITLE
Grid checkbox on children not appropriate

### ISSUE THREAD

**Issue by mootensai** [mootensai/yii2-enhanced-gii#78]
Anybody could fix this at `Active` checkbox?
![checkbox](https://cloud.githubusercontent.com/assets/5844149/17745566/7bd6d5c8-64d6-11e6-85a4-dba752f04947.png)

**Comment by arjenmeijer** [comment]
```
    [
        'class' => '\kartik\grid\BooleanColumn',
        'attribute'=>'active',
        'trueLabel' => 'Yes', 
        'falseLabel' => 'No'
    ],
```

**Comment by mootensai** [comment]
Thanks @arjenmeijer, but your solution not working to me. I've found a way to fix this.
