### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by ksenthilbabu** [mootensai/yii2-enhanced-gii#79]
Installed using composer
1.Yii2 Advance template
2. yii2-enhanced-gii
Installed without any problems.
Also code at your config\main.php.  in frontend also in backend folders modified.
Getting the IO Generator (Model), IO Generator (CRUD) & Migration Generator are displayed in index.php?r=gii

But when i click the IO Generator (Model), Getting Errors
 PHP Fatal Error – yii\base\ErrorException
Class 'mootensai\enhancedgii\model\BaseActiveRecord' not found
@ Line 86
[['modelClass'], 'validateClass', 'params' => ['extends' => BaseActiveRecord::className()]],

`
1. in D:\YiiProjects\YiiTest\vendor\mootensai\yii2-enhanced-gii\model\Generator.php
    public function rules() {
        return array_merge(parent::rules(), [
            [['db', 'nsModel', 'tableName', 'modelClass', 'queryNs'], 'filter', 'filter' => 'trim'],
            [['tableName', 'db'], 'required'],
            [['tableName'], 'match', 'pattern' => '/^(\w+.)?([\w*]+)$/', 'message' => 'Only word characters, and optionally an asterisk and/or a dot are allowed.'],
            [['tableName'], 'validateTableName'],
            [['nsModel', 'baseModelClass', 'queryNs', 'queryBaseClass'], 'match', 'pattern' => '/^[\w\\]+$/', 'message' => 'Only word characters and backslashes are allowed.'],
            [['modelClass', 'baseModelClass', 'db'], 'match', 'pattern' => '/^[\w\\]_$/', 'message' => 'Only word characters and backslashes are allowed.'],
            *_[['modelClass'], 'validateClass', 'params' => ['extends' => BaseActiveRecord::className()]],**
            [['queryBaseClass', 'queryClass'], 'validateClass', 'params' => ['extends' => ActiveQuery::className()]],
            [['db'], 'validateDb'],
            [['enableI18N', 'generateQuery', 'generateLabelsFromComments',
                'useTablePrefix', 'generateMigrations', 'generateAttributeHints', 'generateBaseOnly'], 'boolean'],
            [['generateRelations'], 'in', 'range' => [self::RELATIONS_NONE, self::RELATIONS_ALL, self::RELATIONS_ALL_INVERSE]],
            [['messageCategory'], 'validateMessageCategory', 'skipOnEmpty' => false],

```
        [['skippedColumns', 'skippedRelations',
            'blameableValue', 'nameAttribute', 'hiddenColumns', 'timestampValue',
```
1. yii\base\ErrorHandler::handleFatalError()
   $_GET = [
   'r' => 'gii/default/view',
   'id' => 'enhanced-gii-model',
   ];

$_COOKIE = [
    'advanced-frontend' => 'tgqkppjg2pnfudvc5jhmm68712',
    '_csrf-frontend' => '88f0570f5fcac84536eabc9fe22252705758c470d6118d047cc5ca1eef7d6752a:2:{i:0;s:14:"_csrf-frontend";i:1;s:32:"YzRVLvKLwI8lPYndjqaXIoIj3WmuznOo";}',
];

`

Please kindly guide me to solve this exception

**Comment by mootensai** [comment]
Whoops, I'll fix it tommorow, to fix :
1. Use yii's BaseActiveRecord
Type : `use yii\db\BaseActiveRecord`
2. Comment that line for today and i'll fix that tommorow

**Comment by ksenthilbabu** [comment]
Thanks for the reply,
As you said i included "use yii\db\BaseActiveRecord" to "vendor\mootensai\yii2-enhanced-gii\model\Generator.php" now i am getting 
"Class 'mootensai\enhancedgii\model\ActiveQuery' not found"
Then included "use yii\db\ActiveQuery;" Now it is opening without any problems.

I will test generating the models and CRUD and let you know.

Again thanks for guiding me.

**Comment by ksenthilbabu** [comment]
Hi  mootensai,

When trying to generate model using IO Generator (Model)
Database  -> MySQL
Getting **"Class 'Tblcashiers' does not exist or has syntax error."**
Below the parameters using in IO Generator (Model)
- Table Name : tblcashiers
- Enable I18N=true
- Model Class: Tblcashiers
- Generate ActiveQuery =TRUE
- Generate Relation = ALL Relation
- Generate Attribute Hints = TRUE
- Timestamp Behaviors ->Created At & Updated At = EMPTY
- Blameable Behaviors->Created At & Updated At = EMPTY
- UUID Column =EMPTY

Please guide me thanks

**Comment by ksenthilbabu** [comment]
Hi mootensai,
In IO Generator (CRUD)
Getting 
**" PHP Fatal Error – yii\base\ErrorException "
"Class 'app\models\Tblcashiers' not found"**
IN mootensai\yii2-enhanced-gii\crud\Generator.php @ Line 1020

@**$model = new $this->modelClass();** in below function

```
public function generateSearchLabels() {
    /* @var $model Model */
    **$model = new $this->modelClass();**
    $attributeLabels = $model->attributeLabels();
    $labels = [];
    foreach ($this->getColumnNames() as $name) {
        if (isset($attributeLabels[$name])) {
            $labels[$name] = $attributeLabels[$name];
        } else {
            if (!strcasecmp($name, 'id')) {
                $labels[$name] = 'ID';
            } else {
```

Below the parameters using in IO Generator (CRUD)
- Name : tblcashiers
- Enable I18N=true
- Model Class: Tblcashiers
- Controller Class : TblcashiersController
- Add cancel Button =TRUE
- Search Model Class :TblcashiersSearch

If i uncheck  **Generate Search Model** and generate it generated class without Model Class.
If i check  **Generate Search Model** and generate it error 
**" PHP Fatal Error – yii\base\ErrorException "
"Class 'app\models\Tblcashiers' not found"**
IN mootensai\yii2-enhanced-gii\crud\Generator.php @ Line 1020

**Comment by mootensai** [comment]
Ok thanks for your info..

If you use advance template, you cannot use `app` as your namespace. You
gotta use backend or frontend for your model and controller namespace

**Comment by mootensai** [comment]
Fixed! Thanks
