### ISSUE TITLE
Model class not generating  from IO Generator (Model)

### ISSUE THREAD

**Issue by ksenthilbabu** [mootensai/yii2-enhanced-gii#80]
Hi mootensai,
Using : Yii Advanced template
using composer updated the extension.

Parameters used as below:
- Table name = tblcashiers
- Enable I18N =True
- Message Category = frontend
- Model Namespace=frontend\models
- Model Class=Tblcashiers
- Generate ActiveQuery=True
- ActiveQuery Namespace=frontend\models
- Generate Labels From Comments=True
- Generate Relations=All Relations
- Generate Attribute Hints=True
- Optimistic Lock=lock
- Timestamp Behaviors &
  
  Blameable Behaviors & UUID Column =empty

When i click **PREVIEW**  it show under Model Class  **"Class 'Tblcashiers' does not exist or has syntax error."**

Now i modified : 
Model Class=Empty

When i click **PREVIEW**  it show code Files as below with ACTION =CREATE
1.models\base\Tblcashiers.php
2.models\Tblcashiers.php
3.models\TblcashiersQuery.php 

When i click **Generate**  under Model Class it show **"Class 'Tblcashiers' does not exist or has syntax error."** and not files generated in the path frontend\models

Please kindly guide me (Or) am i doing anything wrong

**Comment by mootensai** [comment]
Could you send me your schema? Works fine with me on my schema now..

**Comment by mootensai** [comment]
OK, I've found the problem! Thanks! Please update and try again
