### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException From IO Generator (CRUD)

### ISSUE THREAD

**Issue by ksenthilbabu** [mootensai/yii2-enhanced-gii#81]
Hi Mootensai

The IO Generator (Model) works fine. Thanks
**Now getting error From IO Generator (CRUD)**
Error : 
Invalid Configuration – yii\base\InvalidConfigException
Unable to locate message source for category 'frontend'.
Database =MySQL
database name : yii2advanced
CREATE TABLE `tblcashiers` (
    `cashierid` INT(11) NOT NULL AUTO_INCREMENT,
    `firstname` VARCHAR(60) NOT NULL,
    `lastname` VARCHAR(60) NOT NULL,
    `password` VARCHAR(60) NOT NULL,
    `emailaddress` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`cashierid`),
    UNIQUE INDEX `emailAddress` (`emailaddress`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
Parameters used as below

Table Name =tblcashiers
Model Namespace=frontend\models
Model Class = Tblcashiers
Skipped Relations=empty
Name Attribute=Empty
Hidden Columns=Empty
Skipped Columns=empty
Enable I18N =True
Message Category = frontend
Controller Namespace=frontend\controllers
Controller Class=TblcashiersController
Expandable Index Grid View=True
PDF Printable View=True
Add Cancel Button On Form=True
Generate Search Model=True
Search Model Namespace=frontend\models
Search Model Class=TblcashiersSearch

When i click **Preview** generating errors (attached pdf for reference)

The Error File as PDF Attached for your kind perusal.

[InvalidConfigException.pdf](https://github.com/mootensai/yii2-enhanced-gii/files/428149/InvalidConfigException.pdf)

**Comment by mootensai** [comment]
That's because u use i18n(internationalization), and you use message
category `frontend`.  Try to generate model without i18n or use i18n with
message category `app`

**Comment by mootensai** [comment]
If you haven't read  [Yii 2 Definitive Guide](http://www.yiiframework.com/doc-2.0/guide-index.html) before, please ask at [gitter](https://gitter.im/mootensai/yii2-enhanced-gii) first..
