### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException From IO Generator (CRUD) 

### ISSUE THREAD

**Issue by ksenthilbabu** [mootensai/yii2-enhanced-gii#83]
HI Mootensai,
sorry for the delay
As per your guidance i checked with 
**Option 1**
Enable I18N =True
Message Category = frontend
Generate Search Model=True
Search Model Namespace=frontend\models\search
Search Model Class=TblcashiersSearch
**Option 2** - as per your suggestion
Enable I18N =True
Message Category = app
Generate Search Model=True
Search Model Namespace=frontend\models\search
Search Model Class=TblcashiersSearch
**Option 3**
Enable I18N =False
Generate Search Model=True
Search Model Namespace=frontend\models\search
Search Model Class=TblcashiersSearch

The same Error is generating **"Invalid Configuration – yii\base\InvalidConfigException
Unable to locate message source for category 'frontend'."**

**Option 4**
When i make **Generate Search Model=False**
with **Enable I18N =True (Or) False** and with **Message Category = app (or) Message Category = frontend**
The Below mentioned file are displayed to create
controllers\TblcashiersController.php  
views\tblcashiers_form.php  
views\tblcashiers_script.php  
views\tblcashiers_search.php  
views\tblcashiers\create.php  
views\tblcashiers\index.php  
views\tblcashiers\update.php  
views\tblcashiers\view.php  
views\tblcashiers_formTblsales.php

So please guide me how i can create model class **TblcashiersSearch** by enabling  **Generate Search Model=True**

**Comment by mootensai** [comment]
Have you regenerate your Models too with i18n message category app?

**Comment by ksenthilbabu** [comment]
Since IO-Generator (CRUD) generates the models by itself, i am Not using IO-Generator (Model) for generating models separately.

**Comment by mootensai** [comment]
But when your run your app, your app will run MVC(model, view, controller)
in single page
