### ISSUE TITLE
created_at behavior not working

### ISSUE THREAD

**Issue by realmarkcross** [mootensai/yii2-enhanced-gii#84]
I have a table called 'branch' in which I've added the created_at behavior through the enhanced gii screen and I've confirmed it exists in the base model, but when I go to add a new record in the branch/create screen, and then try and save it, it says that, 'Created At cannot be blank.'  It seems like the behavior is not working.  This is while adding a new record.

**Comment by mootensai** [comment]
The problem is on your database. You must allow null on your created_at column.
