### ISSUE TITLE
Possible missing instructions

### ISSUE THREAD

**Issue by mmx1947** [mootensai/yii2-enhanced-gii#85]
Composer installed the package fine. In following the readme file, the stock Yii Gii screen continues to display. The readme file has no instructions for modifying the config file for starting gii with the new generator or am I missing something here.

**Comment by mootensai** [comment]
I don't understand what you mean, please give some screenshot. It doesn't need to modify config file for starting gii. It adds new menu on your gii 
![image](https://cloud.githubusercontent.com/assets/5844149/19230970/a3ae489c-8f01-11e6-8bda-3dafc08f008c.png)
