### ISSUE TITLE
dynamic form not save

### ISSUE THREAD

**Issue by mysoundmagic** [mootensai/yii2-enhanced-gii#89]
hello moontensai, dynamic form for schema parent-child/FK did not save

**Comment by mootensai** [comment]
Maybe your database configuration is wrong.. Please check your database configuration. If you can generate relation with official yii2-gii, then you could generate parent-child successfully

**Comment by mysoundmagic** [comment]
i thought my database is ok, after all just a single table.
for example from this screenshot : 
![001](https://cloud.githubusercontent.com/assets/5405947/20697288/877a939c-b62a-11e6-90a3-0ccc8a689ce2.png)
if I create, then it will just save FIN000. FIN 001 and FIN 002 is not saved.

if I create one by one and use combobox parent ID, it running well.
update action:
![002](https://cloud.githubusercontent.com/assets/5405947/20697412/a526052e-b62b-11e6-904c-167e23bead4c.png)
