### ISSUE TITLE
Where to put model rules()?

### ISSUE THREAD

**Issue by mootensai** [mootensai/yii2-enhanced-gii#9]
Where to put model rules()? 
Should i put it on base model or extended model?
Do you like to change your generated rules?
I think i'll put it on the extended model? 
What do you guys think?

**Comment by arjenmeijer** [comment]
I do change the default rules very often. So I agree it should be in the extended model.

**Comment by masterGH** [comment]
Would love an option to put it in either place.  Personally I liked it in the base model as before if for no other reason that leaving the extended model clean.  What is the advantage to moving the rules to the extended model out of curiosity?

**Comment by realmarkcross** [comment]
In the extended model seems to make sense, but why not an option?

**Comment by chitwarnold** [comment]
Extended Model is the best place

**Comment by mootensai** [comment]
After I think about it, what if it's best that i generate on both model and the extended model merge parent rules with extended rules.. so if DB structure is changed, you don't have to type manually the validation of the new column..

what do you guys think?

**Comment by arjenmeijer** [comment]
For me, the difference between model and extended model is complicating the code. Every time I have to ask myself where to put and find things. Give an option to generate just one model with all code in it. Gone are  the questions!

**Comment by mootensai** [comment]
you should not type anything on the base model actually.. base models are for generated by gii only. so u don't have to move any code if you want to re-structure your tables.

on yii 1(i built the related CRUD generator too), i experienced that if i want to restructure the table, I have to backup my functions on the models before i re-generated the models

**Comment by arjenmeijer** [comment]
Well, sometime I have add new complex relations. If I put them in the extended model, I have two places with relations. Mmmm...

**Comment by mootensai** [comment]
```
                                                                                  May I see your complex code as an example?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the 3 Indonesia network.                                                                                                                                                                                                                From: Arjen MeijerSent: Senin, 15 Februari 2016 15.56To: mootensai/yii2-enhanced-giiReply To: mootensai/yii2-enhanced-giiCc: Yohanes CandrajayaSubject: Re: [yii2-enhanced-gii] Where to put model rules()? (#9)Well, sometime I have add new complex relations. If I put them in the extended model, I have two places with relations. Mmmm...
```

—Reply to this email directly or view it on GitHub.

**Comment by arjenmeijer** [comment]
Not complex, but nevertheless. A function to return the name of an id with the id attached. The same function I use everywhere for the select2 pulldown.

```
/**
 * @return array with two fields
 */
public function getIdnameselection()
    {
        $spelvormen = Spelvorm::find()
                    ->orderBy('spelvormname')
                    ->all();
        return ArrayHelper::map($spelvormen, 'spelvorm_id',
            function($model, $defaultValue) {return $model['spelvormname'].' (id: '.$model['spelvorm_id'].')';});
    }
```

**Comment by mootensai** [comment]
Well, basically u dont type anything on the base models.. so that function
better be put on extended models..

**Comment by arjenmeijer** [comment]
Yes, but than I have two places to store getFunctions.  What (logically) differentiates the gii generated ones from the hand coded ones? I my head it are just getFunctions which should be in one place.

**Comment by mootensai** [comment]
so it seems that your functions is for magic getter method. I always put that code on the extended model. 

Logically it's the same, but be warned that your code will be rewritten if you change your DB structure & wants to re-generate the model.

you better move your getFunctions to extended models (manually) if you want to be in one place. (which will override your base model if you re-generate it)

**Comment by arjenmeijer** [comment]
Thanks for the explanation. That is what I am missing most in Yii2. I do not know WHY something is chosen, only that is chosen. Therefore, I can not re-think the decisions and make a correct extension of the thoughts.
