### ISSUE TITLE
null foreign keys

### ISSUE THREAD

**Issue by gvasilopulos** [mootensai/yii2-enhanced-gii#93]
there is another issue when we have a fk that is null on a requested record 
lets say I have a customer who has a contact_id which is id on contacts. it is not necessary for the customer to have a contact_id, but if contact_id is not set on customer table then index.php for customer views break down. 
I think I have a fix 
if customers.contact_id allows null check if ($model->contact) exists if not return null and not customer->contact->id

**Comment by mootensai** [comment]
is it fixed by the pull request? If so I'll close this issue.

**Comment by gvasilopulos** [comment]
yes it is a bit of repeating code, but it works. If you have the time to review it maybe come with a more elegant solution than repeating the code as I do. But if it works, yes it does.

**Comment by mootensai** [comment]
This issue is fixed
