### ISSUE TITLE
Add an option for safeUp and safeDown

### ISSUE THREAD

**Issue by deadmantfa** [mootensai/yii2-enhanced-gii#95]
It will be great if you add a checkbox on the migration form for setting safeUp and safeDown.

**Comment by mootensai** [comment]
How to do that?? I don't think that's possible.. Do you have any idea on how to do that? It'll be cool though if it can..

**Comment by mootensai** [comment]
OH! I get what you mean.. 
It's not that hard.. I'll add it..

**Comment by mootensai** [comment]
Thanks! Sorry it takes so long..
