### ISSUE TITLE
CRUD Generator - Cannot add new record for foreignkey

### ISSUE THREAD

**Issue by zakiyahamza** [mootensai/yii2-enhanced-gii#97]
Hello
I'm newbie for yii2. I tried to use gii-enhanced for one-to-many tables, and success. But, on create form I can't add new record for the table that has -many relation. Any ide ?
Main table : Laporan (one)
Relation table : Komentar (many), Lampiran (many).

Button Add Komentar and Add Lampiran don't work
Thanks

**Comment by mootensai** [comment]
could you send me your mysql dump?

**Comment by mootensai** [comment]
This is most likely because of database design. Please try to use official gii first. If it works by the official gii, the it should be fine with enhanced gii..
